### PR TITLE
add an exclamation point to aboutus

### PR DESCRIPTION
**Pull request by Ivyzhang1998**

### CODE REVIEW

**Comment by Ivyzhang1998** [comment]
final version of Ivy's intro under Section B

**Review by Open-Fuse — APPROVED** [review]

**Review by dayhahm — APPROVED** [review]
Looks good! Where's the last place you traveled to?

**Comment by NickChapman** [comment]
Nice, small change 😄Before submitting can you update the description to be clearer about what exactly it does. Something like "Add an exclamation point to the about us page". It seems silly but it makes it easier to read the history of the changes and understand what each one does.

**Comment by Ivyzhang1998** [comment]
Thanks Nick, I changed it! Hi Debbie, the last place I travelled to is Orlando, where I visited the Universal Studios. Btw could we reply to comments individually?

**Comment by NickChapman** [comment]
I don't think you can respond to comments individually on this main thread. Comments added to code can be replied to individually I think.

**Pull request merged**
